### ISSUE TITLE
[Question] Will you update the pkg to support FreeBSD 14 / OPNsense 24.7.1+

### ISSUE THREAD

**Issue by signo1337** [kulikov-a/opn-monit2t#1]
Hello

Was using the monit2t pkg until I upgraded to OPNsense 24.7.1 and it stopped working probably due to FreeBSD version conflict. At least it says so when removing and trying to reinstall: `pkg: wrong architecture: FreeBSD:13:amd64 instead of FreeBSD:14:amd64`.

I really liked the plugin, so I wanted to ask whether you are planning to update it? 

Thanks.

**Comment by kulikov-a** [comment]
Hi!
will try to look at it this week

**Comment by kulikov-a** [comment]
Hi
made a new package. should work with OPNsense 24.7/FreeBSD:14 now (i hope ;) )
```
pkg delete os-monit2t
pkg add https://github.com/kulikov-a/opn-monit2t/raw/main/work/pkg/os-monit2t-1.1.pkg
```

**Comment by signo1337** [comment]
Heya

Thanks, that was fast :) Siwtched to smtp_to_telegram, but will definitely test the new monit2t.

Best

Aug 19, 2024 7:00:25 PM kulikov-a ***@***.***>:

**Comment by signo1337** [comment]
Confirmed working on 24.7, many thanks
