### ISSUE TITLE
[Improvement] Monit Cache / IP address lookup

### ISSUE THREAD

**Issue by signo1337** [kulikov-a/opn-monit2t#2]
Hey there

I enabled monit2t alerts for Suricata messages: so far it works, and I am happy with it. The only thing, the messages get cut, i.e. the interesting part (signature etc.) is missing. 

Is there a possibility to split the message in several subparts and then sending them one by one, to make sure all information gets submitted?

Furthermore, It would be great if json messages could automatically be parsed.

Here is an example:

`content match:
{"timestamp":"2024-10-time00000","flow_id":abc,"in_iface":"igc0","event_type":"drop","src_ip":"x.x.x.x","src_port":80,"dest_ip":"x.x.x.x","dest_port":61531,"proto":"TCP","pkt_src":"wire/pcap","direction":"to_client","drop":{"len":1500,"tos":0,"ttl":59,"ipid":abc,"tcpseq":abc,"tcpack":3129186272,"tcpwin":501,"syn":false,"ack":true,"psh":false,"rst":false,"urg":false,"fin":false,"tcpres":0,"tcpurgp":0,"reason":"rules"},"tx_id":1,"alert":{"action":"blocked","gid"
...
`

Thanks for your great work :)

**Comment by kulikov-a** [comment]
Hi!
it doesn't looke like plugin script limitation. You can insert some long text in Usage field and send Test message.
I'll try to look at it today (may be some limits on monit side)
![image](https://github.com/user-attachments/assets/dbd0aef6-a1e3-4635-af44-c2b30b082d6a)

**Comment by signo1337** [comment]
Ah nice, good to know. My messages from Suricata are always cropped, like this:

![Screenshot_20241012-140535_Cherrygram](https://github.com/user-attachments/assets/e17b6f8e-6dc3-43eb-b6b3-9e5c707d7b57)

I also plan to use ipinfo.io API to extract src/dest IP information and send it with the Telegram message :)

**Comment by kulikov-a** [comment]
yep, it must have something to do with the monit limits itself. playing with the `fileContentBuffer` value in the monit config gave me this result (you can see what part of the line (or the whole line) monit passes to external script in the monit event log (with Informational severity)):
![image](https://github.com/user-attachments/assets/eafb1226-8f09-405e-b484-edaf515842f9)

https://mmonit.com/monit/documentation/monit.html#LIMITS
https://gist.github.com/bazadactyl/7a4fcf72fafe75cfb3532b76e8333e6d
This Limits is not controlled in the GUI, it must be added directly to the template.
Perhaps adding limits to the GUI makes sense. The opinion of the opsense guys is interesting

**Comment by signo1337** [comment]
> yep, it must have something to do with the monit limits itself. playing with the `fileContentBuffer` value in the monit config gave me this result (you can see what part of the line (or the whole line) monit passes to external script in the monit event log (with Informational severity)): ![image](https://private-user-images.githubusercontent.com/36099472/375966538-eafb1226-8f09-405e-b484-edaf515842f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDY1NjQsIm5iZiI6MTcyODc0NjI2NCwicGF0aCI6Ii8zNjA5OTQ3Mi8zNzU5NjY1MzgtZWFmYjEyMjYtOGYwOS00MDVlLWI0ODQtZWRhZjUxNTg0MmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDE1MTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNTY5NWJlMTZiMTA1NDMzYTE3NTcwYmFjOGVlMjFmZGQzMTZiYTJiZTFlNmNiMjk5NzI0M2RiZjk0ZGUyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xOSJWYV7ycY2rNuWM-ck69TKpLlab-HO0wds3AlgRcc)
> 
> https://mmonit.com/monit/documentation/monit.html#LIMITS https://gist.github.com/bazadactyl/7a4fcf72fafe75cfb3532b76e8333e6d This Limits is not controlled in the GUI, it must be added directly to the template. Perhaps adding limits to the GUI makes sense. The opinion of the opsense guys is interesting

Cool, thanks for checking it. What file did you modify as a quick fix and what value did you choose as buffer? 1024 B? Thanks.

**Comment by kulikov-a** [comment]
yes, setting it like https://github.com/opnsense/core/commit/4d088ef5bdd6ebf1e963a178798c9e6e636992aa and reapplying monit settings is enough for alert strings like this one

**Comment by signo1337** [comment]
> yes, setting it like https://github.com/opnsense/core/commit/4d088ef5bdd6ebf1e963a178798c9e6e636992aa and reapplying monit settings is enough for alert strings like this one

Ok, I changed the monit config, and it works. I also added an additional variable to the monit2t.conf (named token_ip), to accommodate for the ipinfo.io API token. 

Furthermore, I modified the script (monit2t.py) with the help of ChatGPT to send an additional telegram message with any public IP info, if detected:

```
#!/usr/bin/env python3

import sys
import os
import syslog
import requests
import json
import re
import ipaddress  # for IP address validation
from configparser import ConfigParser


def t_send(token, chat_id, message):
    t_url = f'https://api.telegram.org/bot{token}/sendMessage'
    syslog.openlog('monit')
    try:
        resp = requests.post(t_url, json={'chat_id': chat_id, 'text': message, 'parse_mode': 'HTML'})
    except requests.exceptions.Timeout:
        syslog.syslog(syslog.LOG_ERR, 'Telegram API endpoint request timeout')
        sys.exit('Telegram API endpoint request timeout')
    except requests.exceptions.TooManyRedirects:
        syslog.syslog(syslog.LOG_ERR, 'Telegram API endpoint returned error: ' + resp.text)
        sys.exit(resp.text)
    except requests.exceptions.RequestException as e:
        syslog.syslog(syslog.LOG_ERR, 'Telegram API endpoint returned error: ' + resp.text)
        sys.exit(resp.text)
    if resp.status_code == 200:
        syslog.syslog(syslog.LOG_NOTICE, 'Telegram message sent.')
        return resp.text
    else:
        syslog.syslog(syslog.LOG_ERR, 'Telegram API endpoint returned error: ' + resp.text)
        sys.exit(resp.text)


def ip_lookup(ip, token_ip):
    # Query ipinfo.io API to get details about the IP address
    try:
        response = requests.get(f"https://ipinfo.io/{ip}/json?token={token_ip}")
        if response.status_code == 200:
            return response.json()
        else:
            return {"error": "Failed to lookup IP"}
    except requests.RequestException:
        return {"error": "Failed to reach ipinfo.io"}


def is_public_ip(ip):
    # Check if an IP address is public
    try:
        ip_obj = ipaddress.ip_address(ip)
        return not (ip_obj.is_private or ip_obj.is_loopback or ip_obj.is_reserved or ip_obj.is_multicast or ip_obj.is_link_local)
    except ValueError:
        return False


def extract_ips_from_json(message_json):
    """Extract src_ip and dest_ip from the JSON object if present."""
    try:
        json_obj = json.loads(message_json)
        src_ip = json_obj.get("src_ip", None)
        dest_ip = json_obj.get("dest_ip", None)
        return src_ip, dest_ip
    except json.JSONDecodeError:
        return None, None


def extract_ips_from_text(message):
    """Extract any IP addresses from a regular text message."""
    ip_pattern = r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    return re.findall(ip_pattern, message)


def parse_and_lookup(message, token_ip, token, chat_id):
    # Set to keep track of unique public IPs
    unique_ips = set()

    # Check if the message is JSON format and extract src_ip, dest_ip if applicable
    src_ip, dest_ip = extract_ips_from_json(message)
    
    # If no JSON format IPs were found, extract from plain text
    if not src_ip and not dest_ip:
        ips = extract_ips_from_text(message)
    else:
        ips = [src_ip, dest_ip]

    # Filter out non-public IP addresses and avoid duplicates
    for ip in ips:
        if ip and is_public_ip(ip):
            unique_ips.add(ip)

    if unique_ips:
        ip_details = []
        for ip in unique_ips:
            details = ip_lookup(ip, token_ip)
            ip_details.append(f"IP: {ip}, Details: {details}")
        
        # Prepare the second message with IP details
        lookup_message = "Public IP Information:\n" + "\n".join(ip_details)
        t_send(token, chat_id, lookup_message)


t_conf = '/usr/local/opnsense/scripts/OPNsense/Monit2T/monit2t.conf'
if os.path.exists(t_conf):
    cnf = ConfigParser()
    cnf.read(t_conf)
    token = str(cnf['api_settings']['token'])
    chat_id = str(cnf['api_settings']['chat_id'])
    token_ip = cnf['api_settings'].get('token_ip', None)
    message = str(cnf['alert_settings']['message'])

    if len(sys.argv) == 1:
        # Detect environment variables (for templated messages)
        msg_vars = re.findall(r"{([^{]*?)}", message)
        env_vars = {}
        for msg_var in msg_vars:
            env_vars[msg_var] = os.getenv(msg_var, "null").replace('<', '&lt').replace('>', '&gt')

        formatted_message = message.format(**env_vars)
        
        # Send the original message as it is
        t_send(token, chat_id, formatted_message)
        
        # Send the second message with IP information (if public IPs are found)
        parse_and_lookup(formatted_message, token_ip, token, chat_id)
    else:
        # Handle test message
        message = 'This is a test telegram message\nAlerts will be sent in the following format: \n\n' + message
        t_send(token, chat_id, message)

```

Just sharing the code for testing purposes or further ideas. There is probably a lot of room for improvement :) Not for production environments.

![Screenshot_20241012-212838_Cherrygram.png](https://github.com/user-attachments/assets/30d2ec02-6cb5-437b-81e4-db2c65172b21)

Edit: uploaded new script. Checks unique IP addresses only once per message.
