### ISSUE TITLE
[Improvement] Add ability to send messages to topics in a group chat

### ISSUE THREAD

**Issue by 1F33LR41N** [kulikov-a/opn-monit2t#3]
Hey there

can you please add ability to send a messages to topics in group chat?

I have many monitoring messages from many services/bots and it will be very comfortable to split opnsense notifications and address it to own topic in the group.

so, basically we need to add additional form for "message_thread_id" and change the notification link to use message_thread_id if it exists in configuration.

Thanks!

**Comment by kulikov-a** [comment]
Hi!
nice idea. I'll see what I can do )

**Comment by kulikov-a** [comment]
@1F33LR41N 
added to master
can you check with 
```
pkg delete os-monit2t
pkg add https://github.com/kulikov-a/opn-monit2t/raw/main/work/pkg/os-monit2t-1.2.pkg
```
please?)

**Comment by 1F33LR41N** [comment]
Hello! Thx for fast improvement! I was tested it with Opnsense 24.7.10_2, works good as planned. Thank you so much!

**Comment by kulikov-a** [comment]
glad it worked  )
